# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unnayan', '0005_auto_20181121_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_id', models.CharField(blank=True, max_length=255)),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('is_feedback_received', models.BooleanField(default=False)),
                ('submited_date', models.DateTimeField(blank=True, null=True)),
                ('os', models.CharField(max_length=64)),
                ('os_version', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.AppVersions')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feedbackcategory',
            unique_together=set([('app', 'category_text')]),
        ),
    ]
