# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='ack_notif_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='is_acknowledged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='is_feedback_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.NotificationModel'),
        ),
    ]
