# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20181212_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='notification',
        ),
    ]
