# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_token', models.CharField(max_length=255, unique=True)),
                ('package_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_reason', models.BooleanField(default=False)),
                ('invidual_update', models.BooleanField(default=False)),
                ('force_update_soft', models.BooleanField(default=False)),
                ('force_update_hard', models.BooleanField(default=False)),
                ('soft_update_percent', models.IntegerField()),
                ('hard_update_percent', models.IntegerField()),
                ('dialog_text', models.TextField()),
                ('dialog_title', models.TextField()),
                ('dialog_ok_button', models.CharField(default='Ok', max_length=255)),
                ('dialog_cancel_button', models.CharField(default='Cancel', max_length=255)),
                ('play_store_url', models.TextField()),
                ('manual_update', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
            ],
        ),
        migrations.CreateModel(
            name='AppUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_id', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('single_update', models.BooleanField(default=False)),
                ('register_time', models.DateTimeField()),
                ('hard_push_ok', models.DateTimeField()),
                ('soft_push_ok', models.DateTimeField()),
                ('soft_push_cancel_time', models.DateTimeField()),
                ('soft_push_cancel_counter', models.IntegerField()),
                ('reason', models.TextField()),
                ('api_call_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
            ],
        ),
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=255)),
                ('version_code', models.IntegerField()),
                ('is_production', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('banned', models.IntegerField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Client'),
        ),
    ]
