# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_token', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(default='', max_length=255)),
                ('package_name', models.CharField(max_length=255)),
                ('app_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('play_store_url', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_reason', models.BooleanField(default=False)),
                ('individual_update', models.BooleanField(default=False)),
                ('force_update_soft', models.BooleanField(default=False)),
                ('force_update_hard', models.BooleanField(default=False)),
                ('soft_update_percent', models.IntegerField(default=100)),
                ('hard_update_percent', models.IntegerField(default=100)),
                ('soft_update_triggered_time', models.DateTimeField(blank=True, null=True)),
                ('hard_update_triggered_time', models.DateTimeField(blank=True, null=True)),
                ('dialog_text', models.TextField()),
                ('dialog_title', models.TextField()),
                ('dialog_ok_button', models.CharField(default='Ok', max_length=255)),
                ('dialog_cancel_button', models.CharField(default='Cancel', max_length=255)),
                ('play_store_url', models.TextField()),
                ('manual_update', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_id', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('single_update', models.BooleanField(default=False)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('hard_push_ok', models.DateTimeField(blank=True, null=True)),
                ('soft_push_ok', models.DateTimeField(blank=True, null=True)),
                ('soft_push_cancel_time', models.DateTimeField(blank=True, null=True)),
                ('soft_push_cancel_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('api_call_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Reasons')),
            ],
        ),
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=255)),
                ('version_code', models.IntegerField()),
                ('is_production', models.BooleanField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('banned', models.IntegerField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='app_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.AppVersions'),
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unnayan.Client'),
        ),
    ]
