# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0002_auto_20181020_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserinfo',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuserinfo',
            name='version_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuserinfo',
            name='version_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
