# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0003_auto_20181021_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfig',
            name='play_store_url',
        ),
    ]
