# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0003_auto_20180617_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserinfo',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='soft_push_cancel_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
