# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('unnayan', '0004_auto_20180617_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='hard_update_triggered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='soft_update_triggered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='reason',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Reasons'),
        ),
        migrations.AlterField(
            model_name='appversions',
            name='version_code',
            field=models.IntegerField(unique=True),
        ),
    ]
