# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0004_remove_applicationconfig_play_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appversions',
            name='is_feedback_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
