# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0005_auto_20180816_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserinfo',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Reasons'),
        ),
    ]
