# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0005_auto_20181121_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversions',
            name='release_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='appversions',
            name='is_production',
        ),
        migrations.AlterUniqueTogether(
            name='appversions',
            unique_together=set([('app', 'version_code')]),
        ),
    ]
