# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unnayan', '0006_auto_20180816_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
